# \uAC1C\uBC1C\uD658\uACBD \uC124\uC815\uAC12
engine.server.ip=172.17.208.36

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://172.17.208.35:3306/destinyecm_hoban
spring.datasource.username=wisenut
spring.datasource.password=wisenut

logging.level.com.wisenut.ebk.spring=debug
