#\uC6B4\uC601\uC11C\uBC84 \uC124\uC815\uAC12

engine.server.ip=127.0.0.1

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://10.20.30.76:13306/destinyecm_hoban
spring.datasource.username=wisenut
spring.datasource.password=wisenutsearch1!

logging.level.root=info